#!/bin/bash

# The parameter $1 is the backup directory location
# which will be compressed afterward
backup_dir="${1}/apps/piratebox"
mkdir -p "${backup_dir}/"

sudo cp -a /var/www/piratebox/public/uploads/ "${backup_dir}/"

exit 0
