#!/bin/bash

# PirateBox app for YunoHost 
# Copyright (C) 2015 Julien Vaubourg <julien@vaubourg.com>
# Contribute at https://github.com/jvaubourg/piratebox_ynh
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Retrieve arguments
domain=${1}
url_path=/piratebox
opt_deleting=${2}
opt_renaming=${3}
opt_chat=${4}

if [ "${opt_deleting}" == yes ]; then
  opt_deleting=true
else
  opt_deleting=false
fi

if [ "${opt_renaming}" == yes ]; then
  opt_renaming=true
else
  opt_renaming=false
fi

if [ "${opt_chat}" == yes ]; then
  opt_chat=true
else
  opt_chat=false
fi

# Check domain/path availability
sudo yunohost app checkurl ${domain}${url_path} -a piratebox
if [ ! $? -eq 0 ]; then
  exit 1
fi

# Install packages
packages='php5-fpm iptables libnet-dns-perl git'
export DEBIAN_FRONTEND=noninteractive

sudo apt-get --assume-yes --force-yes install ${packages}

if [ $? -ne 0 ]; then
  sudo apt-get update
  sudo apt-get --assume-yes --force-yes install ${packages}
fi

# Copy confs
sudo mkdir -pm 0755 /var/log/nginx/
sudo mkdir -pm 0755 /var/spool/piratebox/
sudo chown www-data: /var/spool/piratebox/

sudo install -b -o root -g root -m 0644 ../conf/nginx_captive-piratebox.conf /etc/nginx/conf.d/captive-piratebox.conf
sudo install -b -o root -g root -m 0644 ../conf/nginx_piratebox.conf "/etc/nginx/conf.d/${domain}.d/piratebox.conf"
sudo install -b -o root -g root -m 0644 ../conf/phpfpm_piratebox.conf /etc/php5/fpm/pool.d/piratebox.conf

# Copy web sources
sudo git clone https://github.com/jvaubourg/php-piratebox.git /var/www/piratebox/

sudo chown -R root: /var/www/piratebox/
sudo chmod -R 0644 /var/www/piratebox/
sudo find /var/www/piratebox/ -type d -exec chmod +x {} \;

sudo install -b -o root -g root -m 0644 ../conf/piratebox_config.php.tpl /var/www/piratebox/config.php

# Fix permissions
sudo chown -R www-data: /var/www/piratebox/public/uploads/
sudo chown -R www-data: /var/www/piratebox/public/chat/

# Fix php-piratebox configuration
sudo sed 's|<TPL:NGINX_REALPATH>|/var/www/piratebox/|g' -i /var/www/piratebox/config.php
sudo sed "s|<TPL:OPT_RENAMING>|$opt_renaming|g" -i /var/www/piratebox/config.php
sudo sed "s|<TPL:OPT_DELETING>|$opt_deleting|g" -i /var/www/piratebox/config.php
sudo sed "s|<TPL:OPT_CHAT>|$opt_chat|g" -i /var/www/piratebox/config.php

# Fix confs
## nginx
sudo sed "s|<TPL:DOMAIN>|${domain}|g" -i /etc/nginx/conf.d/captive-piratebox.conf
sudo sed 's|<TPL:NGINX_REALPATH>|/var/www/piratebox/|g' -i /etc/nginx/conf.d/captive-piratebox.conf
sudo sed 's|<TPL:PHP_NAME>|piratebox|g' -i /etc/nginx/conf.d/captive-piratebox.conf

## php-fpm
sudo sed 's|<TPL:PHP_NAME>|piratebox|g' -i /etc/php5/fpm/pool.d/piratebox.conf
sudo sed 's|<TPL:PHP_USER>|www-data|g' -i /etc/php5/fpm/pool.d/piratebox.conf
sudo sed 's|<TPL:PHP_GROUP>|www-data|g' -i /etc/php5/fpm/pool.d/piratebox.conf
sudo sed 's|<TPL:NGINX_REALPATH>|/var/www/piratebox/|g' -i /etc/php5/fpm/pool.d/piratebox.conf

# Install fakedns
sudo install -o root -g root -m 0755 ../conf/piratebox_fakedns /usr/local/bin/

# Copy init script
sudo install -o root -g root -m 0755 ../conf/init_ynh-piratebox /etc/init.d/ynh-piratebox

# Update firewall
sudo yunohost firewall allow --no-upnp UDP 4253
sudo yunohost firewall allow --no-upnp TCP 4280

# Set default inits
sudo yunohost service add php5-fpm
sudo yunohost service enable php5-fpm

sudo service php5-fpm restart
sudo service nginx reload

sudo yunohost service add ynh-piratebox
sudo yunohost service enable ynh-piratebox
sudo service ynh-piratebox start

# Update SSO
sudo yunohost app setting piratebox skipped_uris -v /
sudo yunohost app ssowatconf

exit 0
