#!/bin/bash

# PirateBox app for YunoHost 
# Copyright (C) 2015 Julien Vaubourg <julien@vaubourg.com>
# Contribute at https://github.com/labriqueinternet/piratebox_ynh
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --time --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
web_port=$(ynh_app_setting_get --app=$app --key=web_port)
dns_port=$(ynh_app_setting_get --app=$app --key=dns_port)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
final_path_admin=$(ynh_app_setting_get --app=$app --key=final_path_admin)
final_path_tmp=$(ynh_app_setting_get --app=$app --key=final_path_tmp)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service..." --time --weight=1
	yunohost service remove $app
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing the systemd service..." --time --weight=1

# Remove the dedicated systemd config
ynh_remove_systemd_config "ynh-piratebox"

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..." --time --weight=1

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression --message="Removing app main directory..." --time --weight=1

# Remove the app directory securely
ynh_secure_remove --file="$final_path"
ynh_secure_remove --file="$final_path_admin"
ynh_secure_remove --file="$final_path_tmp"

# Delete fakedns
ynh_secure_remove --file="/usr/local/bin/piratebox_fakedns"

ynh_secure_remove "/etc/sudoers.d/${app}_ynh"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing nginx web server configuration..." --time --weight=1

# Remove the dedicated nginx config
ynh_secure_remove --file="/etc/nginx/captive-piratebox.conf"

ynh_remove_nginx_config

#=================================================
# REMOVE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Removing php-fpm configuration..." --time --weight=1

# Remove the dedicated php-fpm config
ynh_secure_remove --file="/etc/php/7.0/fpm/pool.d/captive-piratebox.conf"

ynh_remove_fpm_config

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- $web_port$"
then
	ynh_script_progression --message="Closing port $web_port..."
	ynh_exec_warn_less yunohost firewall disallow TCP $web_port
fi
if yunohost firewall list | grep -q "\- $dns_port$"
then
	ynh_script_progression --message="Closing port $dns_port..."
	ynh_exec_warn_less yunohost firewall disallow UDP $dns_port
fi

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE FILES
#=================================================

# Remove the log files
ynh_secure_remove --file="/var/log/$app/"

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression --message="Removing the dedicated system user..." --time --weight=1

# Delete a system user
ynh_system_user_delete --username=$app

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --time --last
