#!/bin/bash

ynh_setting() {
  app=${1}
  setting=${2}

  sudo grep "^${setting}:" "/etc/yunohost/apps/${app}/settings.yml" | sed s/^[^:]\\+:\\s*[\"\']\\?// | sed s/\\s*[\"\']\$//
}

domain=$(ynh_setting piratebox domain)
path=$(ynh_setting piratebox path)
opt_domain=$(ynh_setting piratebox opt_domain)
opt_name=$(ynh_setting piratebox opt_name)
opt_deleting=$(ynh_setting piratebox opt_deleting)
opt_renaming=$(ynh_setting piratebox opt_renaming)
opt_chat=$(ynh_setting piratebox opt_chat)

tmpdir=$(mktemp -dp /tmp/ "${APP}-upgrade-XXXXX")
sudo mv /var/www/piratebox/public/uploads/ "${tmpdir}/"

export PIRATEBOX_UPGRADE=1
sudo bash /etc/yunohost/apps/piratebox/scripts/remove
bash ./install "${domain}" "${path}" "${opt_domain}" "${opt_name}" "${opt_deleting}" "${opt_renaming}" "${opt_chat}"

sudo mv "${tmpdir}/uploads/"* /var/www/piratebox/public/uploads/ 2> /dev/null
sudo rm -r "${tmpdir}/"

sudo systemctl start ynh-piratebox

exit 0
